### ISSUE TITLE
This code doesn't work out the box - 404 error when navigating to the url

### ISSUE THREAD

**Issue by anotherstarburst** [jpetazzo/django#3]
I followed the instructions of 1) clone the repo 2) deploy to dotcloud, however when I navigate to the url given I get a 404 error:

Page not found (404)
Request Method: GET
Request URL:    <URL>
Using the URLconf defined in hellodjango.urls, Django tried these URL patterns, in this order:
^admin/
The current URL, , didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by anotherstarburst** [comment]
I see the problem now, there aren't any pages other than /admin. In this case for the url to work the trailing comma after

```
url(r'^admin/', include(admin.site.urls))
```

must be removed

**Comment by jpetazzo** [comment]
In fact, this is the expected result. It is a very barebones Django example; it doesn't even have a homepage (a view registered for the `/` URI). However, if you go to `/admin`, you will be able to access the Django admin.

Just to let you know—we are rewriting (and updating!) the Django tutorial; it will soon be _much, much_ better.

Thanks for your feedback!
